
export const globalConfigOptionDefaults: Record<string, unknown> = {
  "allowCustomCrateRegistries": false,
  "allowedCommands": [],
  "allowedEnv": [],
  "allowedHeaders": [
    "X-*"
  ],
  "allowedUnsafeExecutions": [],
  "allowPlugins": false,
  "allowScripts": false,
  "allowShellExecutorForPostUpgradeCommands": false,
  "autodiscover": false,
  "bbUseDevelopmentBranch": false,
  "binarySource": "install",
  "cacheHardTtlMinutes": 10080,
  "cachePrivatePackages": false,
  "cacheTtlOverride": {},
  "checkedBranches": [],
  "configValidationError": false,
  "customEnvVariables": {},
  "deleteAdditionalConfigFile": false,
  "deleteConfigFile": false,
  "detectGlobalManagerConfig": false,
  "detectHostRulesFromEnv": false,
  "dockerChildPrefix": "renovate_",
  "dockerMaxPages": 20,
  "dockerSidecarImage": "ghcr.io/renovatebot/base-image:13.102.5",
  "dockerUser": "12021",
  "executionTimeout": 15,
  "exitCodeForErrors": false,
  "exposeAllEnv": false,
  "forceCli": true,
  "forkCreation": true,
  "githubTokenWarn": true,
  "gitNoVerify": [
    "commit",
    "push"
  ],
  "gitTimeout": 0,
  "gitUrl": "default",
  "httpCacheTtlDays": 90,
  "ignorePrAuthor": false,
  "includeMirrors": false,
  "inheritConfig": false,
  "inheritConfigFileName": "org-inherited-config.json",
  "inheritConfigRepoName": "{{parentOrg}}/renovate-config",
  "inheritConfigStrict": false,
  "inheritConfigTrusted": false,
  "internalHostAccess": "warn",
  "mergeConfidenceDatasources": [
    "go",
    "maven",
    "npm",
    "nuget",
    "packagist",
    "pypi",
    "rubygems"
  ],
  "mergeConfidenceEndpoint": "https://developer.mend.io/",
  "migratePresets": {},
  "onboardingBranch": "renovate/configure",
  "onboardingConfig": {
    "$schema": "https://docs.renovatebot.com/renovate-schema.json"
  },
  "onboardingConfigFileName": "renovate.json",
  "onboardingNoDeps": "auto",
  "onboardingPrTitle": "Configure Renovate",
  "onboardingRebaseCheckbox": false,
  "optimizeForDisabled": false,
  "persistRepoData": false,
  "platform": "github",
  "prCacheSyncMaxPages": 100,
  "prCommitsPerRunLimit": 0,
  "presetCachePersistence": false,
  "processEnv": {},
  "productLinks": {
    "documentation": "https://docs.renovatebot.com/",
    "help": "https://github.com/renovatebot/renovate/discussions",
    "homepage": "https://github.com/renovatebot/renovate"
  },
  "rebaseAllOpenBranches": false,
  "reportFormatting": false,
  "repositoryCache": "disabled",
  "repositoryCacheForceLocal": false,
  "repositoryCacheType": "local",
  "requireConfig": "required",
  "s3PathStyle": false,
  "secrets": {},
  "unicodeEmoji": true,
  "useCloudMetadataServices": true,
  "userAgent": "Renovate/{{renovateVersion}} (https://github.com/renovatebot/renovate)",
  "variables": {}
};
